### ISSUE TITLE
Ensure new `loc-mods` gem works with `relaton-nist`

### ISSUE THREAD

**Issue by ronaldtse** [relaton/loc-mods#3]
This gem is now released but it will need some aligning to make sure it works with Relaton-NIST.

Needed by:
* https://github.com/usnistgov/NIST-Tech-Pubs/issues/42

Ping @andrew2net .

_Originally posted by @ronaldtse in https://github.com/relaton/loc-mods/issues/2#issuecomment-2106187772_

**Comment by andrew2net** [comment]
@ronaldtse  Is it parser for MODS files? So the input is MODS file, right?
I see `relaton` in the dependencies. If we are going to use this gem in `relaton-nist` when we need to remove the dependency because `relaton` depends on `relaton-nist` and we got the loop issue:
```sh
bundle install
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Your bundle requires gems that depend on each other, creating an infinite loop. Please remove either gem 'loc-mods' or gem 'relaton' and try again.
```

**Comment by ronaldtse** [comment]
@andrew2net yes, it is a parser for the MODS file, as you can see under `references`.

Let me remove the dependency. I only put it there in case you needed it.

**Comment by andrew2net** [comment]
@ronaldtse the Shale doesn't support `nil` prefix for default namespaces:
```ruby
# lib/loc_mods/collection.rb
...
      namespace "http://www.loc.gov/mods/v3", nil
...
```
So the tests where output XML compares with input fail.
The condition in the Shale doesn't allow prefixes to be nil:
```ruby
# gems/ruby-3.2.0/gems/shale-1.1.0/lib/shale/adapter/nokogiri/document.rb
...
        def add_namespace(prefix, namespace)
          @namespaces[prefix] = namespace if prefix && namespace
        end
...
```
We can monkey patch the method, but do we really need to have the output functional?

**Comment by andrew2net** [comment]
@ronaldtse it seems this gem parses all the second level element the new allrecords.xml has. I only checked second level elements under `modsCollection/mods/*`.
I'm trying to use the datase in https://github.com/relaton/relaton-nist/issues/112
Can we close this issue?

**Comment by andrew2net** [comment]
It works. The new parser is implemented https://github.com/relaton/relaton-nist/issues/112
